# Site settings
title:	Ashley's Space
email:	ashley.piglet@gmail.com
description:	> # this means to ignore newlines until "baseurl:"
  This is my awesome site. Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner:	ashley pickett
email:	ashley.piglet@gmail.com
facebook_username:
twitter_username:
github_username:
address:	123 Hard Road
  - line:	Spokane, WA 
  - line:
  # Feel free to add more lines here 
telephone:
copyright:	2017

# API settings
google_api_key:

# Build settings
markdown: kramdown
